### ISSUE TITLE
Can't teleport to either room with this layout

### ISSUE THREAD

**Issue by BrakeDude** [TazTxUK/MinimapAPI#108]
Arrows are pointing the rooms in question (1 and 2). And because of that you cant teleport to other rooms that are in the right side of level. If we don't use mouse of course. And even with mouse you can't teleport to room 1.
![изображение](https://user-images.githubusercontent.com/89103463/207717325-5a055eba-0eed-4b9f-84f8-6ee1bfa3bac1.png)

**Comment by wofsauge** [comment]
This bug should be fixed now
