### ISSUE TITLE
Map flashes when holding Flip item

### ISSUE THREAD

**Issue by wofsauge** [TazTxUK/MinimapAPI#116]
Bug report on Steam:
![image](https://user-images.githubusercontent.com/245725/212063018-ef840d10-1c2c-42a0-80b8-bb10dda8f4bd.png)

**Comment by wofsauge** [comment]
Error caused by callback interfeerences with other mods.

**Comment by Zamiell** [comment]
maybe the new priority callbacks fixes this?
