### ISSUE TITLE
Map still bugged using glowing Hourglass to go back to a previous floor

### ISSUE THREAD

**Issue by Rchardon** [TazTxUK/MinimapAPI#120]
You can see the error it prints everytime you change room + the map messed up

![Capture](https://user-images.githubusercontent.com/33094562/217382291-4553d99d-0584-492f-9b2d-cded2743ec77.PNG)

**Comment by wofsauge** [comment]
i couldnt reproduce that bug, but i added a safety check to the function now that should make the rewind a bit more robust so that such an error you have cant occur anymore.
Relevant Commit: 5eb34418f54fbaaf8b3559016f1f9efa6edccaa2
