### ISSUE TITLE
Blue map renders non-secret special rooms icons

### ISSUE THREAD

**Issue by epfly6** [TazTxUK/MinimapAPI#127]
![image](https://user-images.githubusercontent.com/36567300/222430150-695c3a51-f08f-4ca3-aef9-d9e1a7036c03.png)

**Comment by Zamiell** [comment]
it should be fixed on latest:
![image](https://user-images.githubusercontent.com/5511220/222493308-62478cb8-da92-450f-a470-e1e0ba7a29b7.png)

**Comment by epfly6** [comment]
> it should be fixed on latest: ![image](https://user-images.githubusercontent.com/5511220/222493308-62478cb8-da92-450f-a470-e1e0ba7a29b7.png)

![image](https://user-images.githubusercontent.com/36567300/222501032-bd0b4fb4-4291-492a-b507-a6bac28295d8.png)
Running from github version, which is up-to-date to workshop version (also disable that horrible fitler xP xP)

**Comment by Zamiell** [comment]
nevermind, i was actually thinking of a different bug

**Comment by wofsauge** [comment]
This issue is fixed now. Thanks for the report :)

**Comment by Zamiell** [comment]
thanks wof
