### ISSUE TITLE
Bug - All runes missing icon

### ISSUE THREAD

**Issue by Zamiell** [TazTxUK/MinimapAPI#13]
1) It's kind of buggy, when a rune first drops nothing will be shown on the minimap, but then if they are swapped out, it will draw a card icon. So that part seems to be a straight-up bug with their current implementation.

2) Runes should have a separate symbol on the minimap. Preferably, one for up-pointing and one for down-pointing and one for black rune.

**Comment by TazTxUK** [comment]
Fixed in commit 00f29f13b36b1e31795a2ffa7d25b8fe9a0984d1
