### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Zamiell** [TazTxUK/MinimapAPI#141]
When using a Get out of Jail Free card in a Boss Rush to escape, I got the following run-time error:

```
[INFO] - Error in "PostUseItem" call: ...rth/mods/minimapi_1978904635/scripts\minimapapi\main.lua:1437: attempt to index a nil value
```

Which corresponds to this function:

![image](https://github.com/TazTxUK/MinimapAPI/assets/5511220/68bb3498-e1e1-4bcf-9fa7-6423637b6046)

**Comment by wofsauge** [comment]
Fixed with commit 6e1071ba992be20a4229245b043dedd4f6de24ee
