### ISSUE TITLE
Feature - Don't group pickup icons (for large minimap)

### ISSUE THREAD

**Issue by Zamiell** [TazTxUK/MinimapAPI#18]
Consider the following room:

![image](https://user-images.githubusercontent.com/5511220/74026696-b3cfde80-4974-11ea-834f-5ab57970c4a3.png)

There are two coins, so MinimapAPI groups the coins by subtype and only displays one coin on the minimap. (This is the vanilla behavior.)

However, this behavior is less useful than it could be - it would be nice to communicate to the player that there are actually **two** coins in the room, instead of just one.

In this room, there are 3/4 "slots" being used, e.g. the slot in the bottom right hand corner is unused. I propose that it might as well be filled in with the extra coin. Generally, if there are slots open/available on the minimap, then the MinimapAPI should not truncate extra pickups via the grouping mechanism.

(The current behavior is fine in the case where there are not enough slots for the additional pickups.)

**Comment by TazTxUK** [comment]
While this may be fairly useful as a feature, the coding rework is too much work for something which so few players have a problem with. I'll leave this issue open for now, but it's not likely we'll work on it anytime soon.

**Comment by TazTxUK** [comment]
This has been implemented in a recent commit.
