### ISSUE TITLE
Dimensions are not supported

### ISSUE THREAD

**Issue by wofsauge** [TazTxUK/MinimapAPI#34]
The new Repentance mechanic of floor dimensions is currently not supported. This causes multiple issues:

1. Higher dimensions overwrite content of the main dimension 0 . Most notable in Flooded Caves 2 + Mirror world and Mines2 + escape sequence.
2. changes to main dimension rooms arent tracked at all if another dimension is present

Code that might help us for detecting such stuff (By Xalum):
```lua
function mod.IsInDimension(num)
    local level = game:GetLevel()
    local id = level:GetCurrentRoomIndex()

    return GetPtrHash(level:GetRoomByIdx(id)) == GetPtrHash(level:GetRoomByIdx(id, num or 0))
end

function mod.IsMirrorStage()
    local level = game:GetLevel()
    return level:GetStage() == LevelStage.STAGE1_2 and level:GetStageType() >= StageType.STAGETYPE_REPENTANCE
end

function mod.IsInMirror() return mod.IsMirrorStage() and mod.IsInDimension(1) end```

**Comment by TazTxUK** [comment]
Fixed
