### ISSUE TITLE
Mirror and Minecart Room Icons should only be visible when the room was entered before

### ISSUE THREAD

**Issue by wofsauge** [TazTxUK/MinimapAPI#44]
Important Feature request from the Speedrunning Community:

Right now, the Mirror and Minecart room icons are visible when in the adjacent room. This should not be the case, since in the main game, you need to enter these rooms to see the icon.

**Comment by TazTxUK** [comment]
fixed in c13df3ddbe1d0a9b6fab91ccd07f54526ea13d50
