### ISSUE TITLE
Recoloured rooms are highlighted on continue.

### ISSUE THREAD

**Issue by Cerandipity** [TazTxUK/MinimapAPI#51]
After a room's color field is changed quitting the run and then continuing it will cause all recolored rooms to be brightly highlighted as though one were in those rooms, but the brightening applies to the entire square the room occupies rather than just the room sprite itself.

Tested with MiniMAPI as only active mod and using red key to generate colored rooms, then exiting run and continuing while outside of the created rooms.

**Comment by wofsauge** [comment]
This bug is fixed now :) thanks for the report
