### ISSUE TITLE
Red rooms showing as normal on 1st floor

### ISSUE THREAD

**Issue by laceous** [TazTxUK/MinimapAPI#63]
I have a mod which creates all red rooms on the map at the start of each floor (using MakeRedRoomDoor). On the first floor, the red rooms show up but don't have the red coloring in the minimap so you can't differentiate them from regular rooms. Strangely, as soon as you go down to the second floor this issue corrects itself, and red rooms show up with a red coloring.

**Comment by laceous** [comment]
The PR I just opened fixes the issue here, but there seems to be a secondary issue specific to the github version of this code. (It works with the version on the workshop.)

The deepcopy that was added recently seems to have a memory issue when filling out the map with red rooms. Here's the log line:
`[Minimap API] Error in "PostGameStart" call: not enough memory`

**Comment by wofsauge** [comment]
will look into the memory overflow some time soon.
