### ISSUE TITLE
Highlight furthest room not working

### ISSUE THREAD

**Issue by TheChilliPL** [TazTxUK/MinimapAPI#65]
![image](https://user-images.githubusercontent.com/18823939/168153242-b645c3dd-ff86-4d48-a003-48606e86c386.png)

The highlight furthest room option doesn't seem to do anything. Also, what is the reason it was added?

**Comment by wofsauge** [comment]
ive fixed this issue now. thanks for the report.

The feature was intended for speedrunning purposes, to highlight the room furthest away from you. that information can either be used to look for boss rooms, or for backtracking purposes.
![image](https://user-images.githubusercontent.com/245725/168926934-667a714c-a3d0-4610-bf90-309dfce28997.png)
