### ISSUE TITLE
Rooms made after the floor loads are shown as red on the map even if they're not red anymore

### ISSUE THREAD

**Issue by sgjd01** [TazTxUK/MinimapAPI#71]
You can use RoomDescriptor.Flags to check if a room is red instead of automatically assuming it's red if it was created after the level has loaded

**Comment by wofsauge** [comment]
this bug should be fixed already, since we only aply the red color when that flag is set. please reopen this issue if you have an example where this bug occurs.
and please note that the "furthest room" indicator is also red, so maybe you mixed them up ;)
