### ISSUE TITLE
Option to change transparency of the map

### ISSUE THREAD

**Issue by wofsauge** [TazTxUK/MinimapAPI#79]
Changing transparency of overlapping sprites might look weird, so that effect should be tested first.

**Comment by Gemboat** [comment]
To add to this -- in the vanilla game, when the map is set to large mode, it's always semi-transparent (unless the map key's being held).
As I'm one of those weirdos who plays with the large map up all the time, this is a deal-breaking issue with minimapi, as I often find the top-right of the screen getting obscured. Obviously 'hide map during combat' helps, but even after a room's cleared there'll sometimes be pickups up there.

**Comment by BrakeDude** [comment]
> Changing transparency of overlapping sprites might look weird, so that effect should be tested first.](https://github.com/TazTxUK/MinimapAPI/issues/79#issue-1324898568)

This is what it looks like with outlines
![Transparent](https://user-images.githubusercontent.com/89103463/185863354-b33114ac-a758-4b71-82ee-785587353c5f.png)

And this is without them
![изображение](https://user-images.githubusercontent.com/89103463/185863692-34c61737-3492-422a-b7e0-99416bc61094.png)

**Comment by wofsauge** [comment]
Implemented by @BrakeDude with commit f7e63b2b031c90fa28272164cf6afad55899f185

Shadow bug is fixed now, by simply turning it off when map is not opaque
