### ISSUE TITLE
Curse Rooms can be freely entered and exited with "NiceJourney"

### ISSUE THREAD

**Issue by namishere** [TazTxUK/MinimapAPI#80]
Players can avoid damage from curse rooms by traveling to and from it with the map teleport feature instead of through the door.

**Comment by wofsauge** [comment]
nice work with fixing it! code looked good. Ive sligtly edited it now tho, in order to implement your TODO, and added a config / MCM option to toggle the damage on and off. otherwise, it was good 👍
