### ISSUE TITLE
Mines/Ashpit 2 causes errors

### ISSUE THREAD

**Issue by MajorCooke** [TazTxUK/MinimapAPI#87]
Simply go to Mines 2 or Ashpit 2 in console, and you'll get this error:

`[INFO] - [Minimap API] Error in "PostLevelLoad" call: ...rth/mods/minimapi_1978904635/scripts/minimapapi/main.lua:605: GetRoomDescFromListIndex: unknown error with index 6`

**Comment by wofsauge** [comment]
that bug was fixed with the newest workshop release already. Are you sure you have the version 2.27 installed already? it was released on the 01. august

**Comment by MajorCooke** [comment]
Yep.

**Comment by wofsauge** [comment]
This issue got fixed now. I will push it to the workshop this weekend
