### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by namishere** [TazTxUK/MinimapAPI#89]
Not really sure what's happening here, but at times my map will show nothing and then crash when trying to expand it. I didn't even think that curse of the lost could be related at first because I have a mod to explicitly disable that, but a couple workshop users are reporting this too.

Another user got a crash at `gameroom:GetBossID()` in nicejourney.lua. I think this is my bad, I saw recently that `Room()` shouldn't be cached and can cause issues otherwise.

**Comment by wofsauge** [comment]
Thanks for the report.
it hopefully got fixed now with commit [d208edf](https://github.com/TazTxUK/MinimapAPI/commit/d208edf323c78f0a836d565e9ac3d7c86db5affc)

hopefully the crashes dont occur anymore :)
