### ISSUE TITLE
Map mode toggle while game is paused, desyncs from Found HUD

### ISSUE THREAD

**Issue by esdeka** [TazTxUK/MinimapAPI#95]
The vanilla implementation of the map toggle doesn't allow to change the map mode while the game is in the pause menu. This means the Found HUD will not be moved up/down to compensate for the map.

The mod doesn't seem to check if the game is paused while toggling, which seems to cause a bug that the Found HUD ends up in the area of the big map.

Not at home atm, but I can take some example screenshots later if needed

**Comment by wofsauge** [comment]
Bug was fixed with commit 8a7e4db18021178e4445aa0351edcd3a0831fb87. Thank you for the report :)
